- name: Gather facts
  hosts: all
  gather_facts: true
  tasks:
  - name: Collect only selected facts
    ansible.builtin.setup:
      filter:
        - 'ansible_distribution'
        - 'ansible_machine_id'
        - 'ansible_*_mb'
    cacheable: true
