---
- name: install software package
  hosts: all
  gather_facts: false
  tasks:
  - name: Install software
    ansible.builtin.package:
      name:
        - "{{ my_pkg_name }}"
      state: latest

