---
- name: install software package
  hosts: all
  gather_facts: true
  tasks:
  - name: install basic packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items: "{{ my_packages }}"
      

