---
- name: Subscription
  hosts: all
  gather_facts: false
  tasks:
  - name: Register as user (joe_user) with password (somepass) and auto-subscribe to available content.
    ansible.builtin.shell: subscription-manager unregister
